# Generated by Django 5.2.4 on 2025-08-06 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categorie', models.CharField(choices=[('entree', 'Entrée'), ('plat', 'Plat principal'), ('dessert', 'Dessert'), ('boisson', 'Boisson')], max_length=20)),
                ('disponibilite', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='plats/')),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
    ]
