# Generated by Django 5.2.4 on 2025-08-09 21:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categorie', models.CharField(choices=[('entree', 'Entrée'), ('plat', 'Plat principal'), ('dessert', 'Dessert'), ('boisson', 'Boisson'), ('glass', 'Glass'), ('africain', 'Africain')], max_length=20)),
                ('disponibilite', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='plats/')),
                ('temps_preparation', models.IntegerField(default=30, help_text='Temps de préparation en minutes')),
                ('ingredients', models.TextField(blank=True, help_text='Liste des ingrédients')),
                ('allergenes', models.CharField(blank=True, help_text='Allergènes présents', max_length=200)),
                ('calories', models.IntegerField(blank=True, help_text='Calories par portion', null=True)),
                ('portion', models.CharField(blank=True, help_text='Taille de la portion', max_length=50)),
                ('difficulte', models.CharField(choices=[('facile', 'Facile'), ('moyen', 'Moyen'), ('difficile', 'Difficile')], default='moyen', max_length=20)),
                ('temps_cuisson', models.IntegerField(blank=True, help_text='Temps de cuisson en minutes', null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('nombre_avis', models.IntegerField(default=0)),
                ('en_promotion', models.BooleanField(default=False, verbose_name='En promotion')),
                ('prix_promotionnel', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Prix promotionnel')),
                ('date_debut_promotion', models.DateTimeField(blank=True, null=True)),
                ('date_fin_promotion', models.DateTimeField(blank=True, null=True)),
                ('pourcentage_reduction', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Pourcentage de réduction')),
                ('description_promotion', models.TextField(blank=True, verbose_name='Description de la promotion')),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créateur')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plats', to='structures.structures')),
            ],
            options={
                'verbose_name': 'Plat',
                'verbose_name_plural': 'Plats',
                'ordering': ['nom'],
            },
        ),
    ]
