# Generated by Django 5.2.4 on 2025-08-25 18:15

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0001_initial'),
        ('structures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='plats',
            name='categorie',
            field=models.CharField(choices=[('entree', 'Entrée'), ('plat', 'Plat principal'), ('dessert', 'Dessert'), ('boisson', 'Boisson'), ('glass', 'Glass'), ('africain', 'Africain')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='plats',
            name='date_creation',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='plats',
            name='date_debut_promotion',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='plats',
            name='date_fin_promotion',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='plats',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='plats',
            name='disponibilite',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='plats',
            name='en_promotion',
            field=models.BooleanField(db_index=True, default=False, verbose_name='En promotion'),
        ),
        migrations.AlterField(
            model_name='plats',
            name='nom',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='plats',
            name='note_moyenne',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddIndex(
            model_name='plats',
            index=models.Index(fields=['categorie', 'disponibilite'], name='plats_plats_categor_dad162_idx'),
        ),
        migrations.AddIndex(
            model_name='plats',
            index=models.Index(fields=['en_promotion', 'disponibilite'], name='plats_plats_en_prom_357fc5_idx'),
        ),
        migrations.AddIndex(
            model_name='plats',
            index=models.Index(fields=['createur', 'structure'], name='plats_plats_createu_b6467f_idx'),
        ),
        migrations.AddIndex(
            model_name='plats',
            index=models.Index(fields=['date_creation', 'date_modification'], name='plats_plats_date_cr_9a79b0_idx'),
        ),
    ]
