# Generated by Django 5.2.5 on 2025-08-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plats',
            name='heure_debut_promotion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plats',
            name='heure_fin_promotion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
