# Generated by Django 5.2.4 on 2025-08-06 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('heure_ouverture', models.CharField(blank=True, max_length=100, null=True)),
                ('heure_fermeture', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('restaurant', 'Restaurant'), ('cafe', 'Café'), ('bar', 'Bar'), ('hotel', 'Hôtel'), ('autre', 'Autre')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='structures/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField(default=False, verbose_name='Mettre en avant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure', to='accounts.user')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
