# Generated by Django 5.2.5 on 2025-08-13 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Structures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(choices=[('Lomé', 'Lomé'), ('Kara', 'Kara'), ('Sokodé', 'Sokodé'), ('Atakpamé', 'Atakpamé'), ('Tsévié', 'Tsévié'), ('Aného', 'Aného'), ('Mango', 'Mango'), ('Dapaong', 'Dapaong'), ('Autre', 'Autre')], max_length=100)),
                ('heure_ouverture', models.CharField(blank=True, max_length=100, null=True)),
                ('heure_fermeture', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('restaurant', 'Restaurant'), ('fastfood', 'Fast Food'), ('cafe', 'Café'), ('boulangerie', 'Boulangerie'), ('traiteur', 'Traiteur'), ('autre', 'Autre')], max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='structures/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField(default=False, verbose_name='Mettre en avant')),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Note moyenne')),
                ('nombre_avis', models.IntegerField(default=0, verbose_name="Nombre d'avis")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
                'constraints': [models.UniqueConstraint(fields=('user',), name='unique_structure_per_user')],
            },
        ),
    ]
