# Generated by Django 5.2.5 on 2025-08-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structures',
            name='type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('hôtel', 'Hôtel'), ('cafe', 'Café'), ('boulangerie', 'Boulangerie'), ('bar', 'Bar'), ('kiosque', 'Kiosque'), ('autre', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='structures',
            name='ville',
            field=models.CharField(choices=[('Lomé', 'Lomé'), ('Kara', 'Kara'), ('Sokodé', 'Sokodé'), ('Atakpamé', 'Atakpamé'), ('Tsévié', 'Tsévié'), ('Aného', 'Aného'), ('Mango', 'Mango'), ('Dapaong', 'Dapaong'), ('Autre', 'Autre')], max_length=20),
        ),
    ]
