# Generated by Django 5.2.4 on 2025-08-09 16:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('brouillon', 'Brouillon')], default='brouillon', max_length=20)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créateur')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='structures.structures')),
            ],
            options={
                'ordering': ['date_creation'],
            },
        ),
    ]
