# Generated by Django 5.2.5 on 2025-08-13 10:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plats', '0001_initial'),
        ('structures', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now)),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plats.plats')),
            ],
            options={
                'verbose_name': 'Association menu-plat',
                'verbose_name_plural': 'Associations menu-plats',
            },
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('brouillon', 'Brouillon')], default='brouillon', max_length=20)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créateur')),
                ('plats', models.ManyToManyField(blank=True, related_name='menus', through='menus.MenuPlat', to='plats.plats')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='structures.structures')),
            ],
            options={
                'ordering': ['date_creation'],
            },
        ),
        migrations.AddField(
            model_name='menuplat',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.menus'),
        ),
        migrations.AlterUniqueTogether(
            name='menuplat',
            unique_together={('menu', 'plat')},
        ),
    ]
